[versions]
agp = "9.0.1"
kotlin = "2.3.10"
appcompat = "1.7.1"

coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
serializationJson = "1.10.0"
androidxWebkit = "1.15.0"

[libraries]
# Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }

# WebKit
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "androidxWebkit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }